yellowclass/yc_app_utils

lib/ui/components/decorators/dashed_line.widget.dart, lib/ui/components/decorators/decorators.import.dart, lib/ui/ui.dart
YT-7910 Dashed Line support added
=> YT-7910 Dashed Line Added

example/android/local.properties, lib/ui/components/video_player/video_player_side_menu_widget.dart
=> Work in Progress

example/pubspec.lock, lib/ui/components/styled_components/styled_image.widget.dart, pubspec.yaml
=> shimmer omg

example/android/local.properties, lib/models/video_player/video_player_options.model.dart, lib/ui/components/video_player/video_player_side_menu_widget.dart
=> video player options

lib/models/embedded_media.model.dart
=> isLooping added in embedded media model

lib/helpers/common_helpers.dart, lib/models/styled_component/v2_styled_text.model.dart
=> styled text widget from text style

lib/helpers/common_helpers.dart
=> create helper to get alignment from list of integer

lib/ui/styleguide/colors.dart
=> tangerine colors added

lib/models/styled_component/styled_video.model.dart
=> loopCount added in styled video

lib/ui/components/form_components/styled_text_field.widget.dart
Name Onboarding screen - keyboard opening automatically to ask user to enter name
=> Keyboard autofocus for onboarding screen [YT-10948]

lib/models/bootstrap_section/bootstrap_section.model.dart
Part of YT-10994, to handle form inputs
=> Added miscParams to bootstrap section model [YT-10994]

lib/models/form_component/styled_input_field.model.dart, lib/ui/components/form_components/styled_text_field.widget.dart
Added option to hide underline in text form field. Part of [YT-10994]
[YT-10994]: https://ivypods.atlassian.net/browse/YT-10994?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Added option to hide underline in text form field

lib/helpers/common_helpers.dart, lib/models/form_component/option.model.dart, lib/models/form_component/styled_radio_field.model.dart, lib/ui/components/bootstrap_section/bootstrap_child.widget.dart, lib/ui/components/form_components/styled_radio_field.widget.dart, lib/ui/components/styled_components/styled_component.widget.dart
=> Fixed button not working issue when there is a form in the bootstrap widget and added support for updated model of styled radio field

lib/models/form_component/styled_input_field.model.dart, lib/ui/components/form_components/styled_radio_field.widget.dart, lib/ui/components/form_components/styled_text_field.widget.dart
Added support for optional styled input field inside radio field
=> Added support for optional styled input field inside radio field

lib/models/styled_component/generic_button_v3.model.dart, lib/ui/components/generic_button/generic_button_v3.widget.dart
=> Added support for highlight elevation

lib/models/styled_component/generic_button_v3.model.dart, lib/ui/components/generic_button/generic_button_v3.widget.dart
=> Added support for splash color

lib/models/click_action/one_click_action.model.dart
=> redirection type enum added in one click action

example/lib/boot_strap_screen/bootstrap_screen.dart, lib/models/styled_component/styled_component.model.dart, lib/typedefs/shared.typedefs.dart, lib/ui/components/bootstrap_section/bootstrap_child.widget.dart, lib/ui/components/bootstrap_section/bootstrap_section.widget.dart, lib/ui/components/styled_components/styled_component.widget.dart
=> added key in styled Component

lib/models/styled_component/generic_button_v3.model.dart, lib/ui/components/form_components/styled_text_field.widget.dart, lib/ui/components/generic_button/generic_button_v3.widget.dart
=> Option to add prefilled text in the text field [YT-11137]

lib/models/styled_component/styled_lottie.model.dart, lib/ui/components/styled_components/styled_lottie.widget.dart, pubspec.yaml
=> add startoffset in lottie

lib/models/styled_component/styled_circular_progress.model.dart, lib/models/styled_component/styled_component.model.dart
=> styled_circular_progress.model.dart added

lib/models/styled_component/styled_circular_progress.model.dart
=> percentage added

lib/models/styled_component/styled_circular_progress.model.dart
=> innerTexts

lib/ui/components/styled_components/styled_circular_progress.widget.dart, lib/ui/components/styled_components/styled_component.widget.dart
=> styled_circular_progress.widget.dart added

lib/ui/components/form_components/styled_autocomplete_field.widget.dart
=> auto complete loader

lib/ui/components/form_components/styled_autocomplete_field.widget.dart, lib/ui/components/form_components/styled_datetime_field.widget.dart
=> date time fix

lib/ui/components/styled_components/styled_lottie.widget.dart
=> lottie in premium page fix

lib/models/form_component/styled_input_field.model.dart, lib/ui/components/form_components/styled_text_field.widget.dart
=> add - in mobile number

lib/models/bootstrap_section/bootstrap_section.model.dart, lib/models/bootstrap_section/bootstrap_section_child.model.dart, lib/ui/components/bootstrap_section/bootstrap_child.widget.dart, lib/ui/components/bootstrap_section/bootstrap_section.widget.dart, lib/ui/components/form_components/styled_select_field.widget.dart
=> edit profile changes

lib/models/bootstrap_section/bootstrap_section.model.dart
=> add copy with in bootstrap

lib/models/styled_component/styled_lottie.model.dart, lib/ui/components/styled_components/styled_component.widget.dart, lib/ui/components/styled_components/styled_lottie.widget.dart
=> clipRRect in lottie

lib/helpers/common_helpers.dart
=> add blur style

lib/models/form_component/form_component.model.dart, lib/models/form_component/styled_rating_slider.model.dart, lib/ui/components/form_components/form_component.widget.dart, lib/ui/components/form_components/styled_rating_slider.widget.dart
=> rating slider added in form components

example/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java, example/ios/Runner/GeneratedPluginRegistrant.m, example/pubspec.lock, lib/models/click_action/v2_click_action.model.dart, lib/ui/components/form_components/styled_rating_slider.widget.dart, pubspec.yaml
=> add vibration in v2 click action, feat/YT-11864

lib/helpers/common_helpers.dart
=> colorToHex added

lib/helpers/common_helpers.dart
=> testing-testing-tags

lib/helpers/common_helpers.dart, pubspec.yaml
=> testing-testing-tags build bump

.github/workflows/release.yml
=> release tag

lib/ui/components/form_components/styled_datetime_field.widget.dart
=> unsaved changes

lib/models/media_manager_info.model.dart
=> start time end time in audio url

example/android/local.properties, lib/models/form_component/form_component.model.dart, lib/models/form_component/styled_points_picker.model.dart, lib/ui/components/form_components/form_component.widget.dart, lib/ui/components/form_components/styled_points_picker.widget.dart
=> styled points picker added

lib/ui/components/form_components/form_component.widget.dart, lib/ui/components/form_components/styled_points_picker.widget.dart
=> inner click action added  in points picker  widget

lib/ui/components/form_components/form_component.widget.dart, lib/ui/components/form_components/styled_points_picker.widget.dart
=> error resolved

lib/models/form_component/styled_select_field.model.dart, lib/ui/components/form_components/form_component.widget.dart, lib/ui/components/form_components/styled_select_field.widget.dart
=> change course

lib/ui/components/form_components/styled_select_field.widget.dart
=> onChange only when value is changed

lib/ui/components/form_components/styled_select_field.widget.dart
=> fix language change dropdown

lib/helpers/common_helpers.dart
=> capitalizeFirstLetter added

lib/ui/styleguide/colors.dart
=> colors add

lib/ui/styleguide/colors.dart
=> add color for dark theme

lib/models/form_component/styled_input_field.model.dart, lib/ui/components/form_components/styled_text_field.widget.dart
=> autoValidateMode

lib/models/click_action/toast_data.model.dart
=> height in toast data

example/pubspec.lock, lib/models/click_action/event_data.model.dart
=> isRevenueEvent added in event data

lib/models/click_action/event_data.model.dart
=> isRevenueEvent

lib/models/styled_component/rich_text.model.dart
=> copy with in rich text
